package com.grupo21.rescuesync.model;

public enum Permiso {

    CREAR_LOTE,
    EDITAR_LOTE,
    BORRAR_LOTE,
    CONSULTAR_LOTES,

    CREAR_OFERTA,
    EDITAR_OFERTA,
    CONSULTAR_OFERTAS,

    REGISTRAR_EMERGENCIA,
    PUBLICAR_EMERGENCIA,
    CONSULTAR_EMERGENCIAS
}